version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - devSecNetwork
    restart: always
    environment:
      - FLASK_ENV=development

networks:
  devSecNetwork:
    external: true
